// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
)

// Injectors from wire.go:

func InitG(ctx context.Context) (G, error) {
	ab, err := ComputeAB(ctx)
	if err != nil {
		return "", err
	}
	c, err := ComputeC(ctx, ab)
	if err != nil {
		return "", err
	}
	def, err := ComputeDEF(ctx, c)
	if err != nil {
		return "", err
	}
	g, err := ComputeG(ctx, def)
	if err != nil {
		return "", err
	}
	return g, nil
}
